[package]
name = "mediumrare"
version = "0.1.0"
edition = "2021"
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
lambda_http = "0.5.1"
tokio = "1.8.1"
ureq = { version = "2.1.1", features = ["json", "tls"] }

[[bin]]
name = "bootstrap"
path = "src/main.rs"
