name: Deploy

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    uses: ./.github/workflows/verify.yml

  deploy:
    needs: verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup rust musl targets
      run: rustup target add x86_64-unknown-linux-musl
    - name: Install musl-gcc
      run: sudo apt install -y musl-tools
    - name: build release
      run: cargo build --release
    - name: build deployable zip file
      run: mv target/x86_64-unknown-linux-musl/release/bootstrap bootstrap && strip bootstrap && zip deploy.zip bootstrap
    - name: upload release build
      uses: actions/upload-artifact@v6.0.0
      with:
        name: mediumrare-serve.zip
        path: deploy.zip
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: update aws lambda code
      run: aws lambda update-function-code --function-name arn:aws:lambda:eu-central-1:999013477667:function:mediumrare-serve --zip-file fileb://deploy.zip
